### ISSUE TITLE
generate_version.sh sources /etc/profile possibly? changes the environment

### ISSUE THREAD

**Issue by astatide** [fmihpc/vlasiator#959] opened 2024-05-06 12:12 UTC
Hola hola!

Not sure if it's an issue on more than just MareNostrum 5, but there might be a line that could catch users unawares in the generate_version.sh: https://github.com/fmihpc/vlasiator/blob/583b8cede3d8a04f9d3dfc61a7574e9b8e7deb37/generate_version.sh#L22

this could cause issues on machines where a default set of modules are loaded via the profile, particularly for compilers.  It might be worth mentioning this in the isntall documentation (unless I missed it) as a user may well already have their modules set and depending on the cluster/computer, this might either generate errors or override the loaded compilers!

(for instance, as the default on MN5 is Intel, using gcc is fine because it just refuses to load the intel modules; however, if I'm using the intel compilers but not the 'default' selection, it'll end up running at least that script with the wrong version.

What isn't clear to me is whether these potential module changes persist beyond the running of generate_version.sh, or whether that occurs in an isolated environment and once that make task is run it goes back to the parent environment.  So, sorry if it's a false issue : )

**Comment by ursg** [comment] 2024-05-06 20:16
Ah, interesting find. We have never run into problems of this kind ourselves, but I can see how it could confuse the build process. (In most cases, we just ignore errors caused by generate_version.sh, which is maybe not the best style).

Anyway, looking at the git blame output for this file, it seems it has been there "forever", even before I joined the Vlasiator project, and the reason for its inclusion has been lost to the ages. So I suggest we just drop it, see if CI builds still work fine, and continue.

**Comment by ykempf** [comment] 2024-05-07 13:29
Agreed, this is a (pre)historic remnant, do post a PR removing this line.

**Comment by astatide** [comment] 2024-05-08 05:53
Will do! : D

**Comment by ursg** [comment] 2024-05-13 10:12
Fixed by #963

**Closed by ursg** 2024-05-13 10:12 UTC
